---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: hibernation-job-
spec:
  template:
    spec:
      serviceAccountName: hibernator
      containers:
      - name: worker
        image: quay.io/jpacker/hibernation-curator:latest
        command: ['python','action.py']
        env:
        - name: TAKE_ACTION
          value: Hibernating
        - name: PYTHONWARNINGS
          value: "ignore:Unverified HTTPS request"  
      restartPolicy: OnFailure